---
name: Feature request
about: Request a feature
title: ''
labels: "\U0001F195 feature request"
assignees: ''
---
## Problem(s) addressed

## Proposed solution(s)

## Alternative solution(s)

## Additional context

\<e.g., copied & pasted shell commands & output>

\<e.g., screenshots only if cannot copy & paste>
