#
# .github/workflows/build-test.yml
#
---
name: Build, Test, and Lint
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  build-test:
    name: Build, Test, and Lint
    runs-on: macos-15
    defaults:
      run:
        # Force all run commands to not use Rosetta 2
        shell: arch -arm64 /bin/zsh -Negku {0}
    steps:
      - uses: actions/checkout@v4
        with:
          # Include all history & tags for script/version
          fetch-depth: 0

      - name: Bootstrap
        run: script/bootstrap

      - name: Build
        run: script/build

      - name: Test
        run: script/test

      - name: Lint
        run: script/lint
