#
# .github/workflows/release.yml
#
---
name: release
on:
  push:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]
jobs:
  release:
    runs-on: macos-14
    steps:

      - run: |
          echo "release event"
          echo "Name: ${{ github.event.release.name }}"
          echo "Description: ${{ github.event.release.body }}"

      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0
      - name: 👢 Bootstrap
        run: script/bootstrap

      # Important to trigger a universal build first as package just works with
      # the `mas` binary in finds in the build dir.
      - name: 🏗️ Build Universal
        run: script/build --universal
      - name: 📦 macOS Package
        run: script/package
      - name: 🚀 Upload mas.pkg
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: mas.pkg
          path: .build/mas.pkg

      - name: 🍼 Homebrew Bottles for mas tap
        run: script/bottle
      - name: 🚀 Upload Bottles
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: homebrew-bottles
          path: |
            .build/bottles/mas-*.bottle.tar.gz

      - name: 🍺 Update Homebrew mas formula
        run: script/brew_formula_update
