#
# .github/workflows/release.yml
#
---
name: release
on:
  release:
    types: [published]
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/zsh {0}
env:
  PRERELEASE: ${{contains(github.event.release.tag_name, '-') && '--prerelease' || ''}}
  TAG_NAME: ${{github.event.release.tag_name}}
jobs:
  release:
    runs-on: macos-15
    steps:
      - name: 🛒 Checkout mas repo
        uses: actions/checkout@v4

      - name: 👢 Bootstrap
        run: |
          script/bootstrap

      - name: 📦 Build universal executable & package it in mas.pkg
        run: |
          script/package

      - name: 📤 Upload mas.pkg
        run: |
          gh release upload "${TAG_NAME}" .build/mas.pkg

      - name: 🚰 Bump mas-cli/tap/mas formula
        run: |
          brew tap mas-cli/tap
          brew bump-formula-pr \
            --tag "${TAG_NAME}" \
            --revision "$(git rev-parse "${TAG_NAME}")" \
            --no-fork \
            --no-browse \
            --online \
            --strict \
            --verbose \
            mas-cli/tap/mas

      - name: 🍺 Bump homebrew-core/mas formula
        if: ${{!env.PRERELEASE}}
        run: |
          brew bump-formula-pr \
            --tag "${TAG_NAME}" \
            --revision "$(git rev-parse "${TAG_NAME}")" \
            --fork-org mas-cli \
            --no-browse \
            --online \
            --strict \
            --verbose \
            mas
