#
# .github/workflows/release.yml
#
---
name: release
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/bash --noprofile --norc -eo pipefail {0}
on:
  release:
    types: [published]
env:
  DRY_RUN: ""
  RELEASE_TAG: ${{github.event.release.tag_name}}
jobs:
  start:
    runs-on: macos-15
    steps:
      - name: 🔈 Log real release event
        # Run only for a real release event
        if: ${{github.event.release.name}}
        env:
          RELEASE_NAME: ${{github.event.release.name}}
          RELEASE_COMMITISH: ${{github.event.release.target_commitish}}
          RELEASE_BODY: ${{github.event.release.body}}
        run: |
          printf $'Triggered by release publication event:\nname: %s\ntag_name: %s\ntarget_commitish: %s\nbody:\n%s\n' \
            "${RELEASE_NAME}" "${RELEASE_TAG}" "${RELEASE_COMMITISH}" "${RELEASE_BODY}"

  pkg-installer:
    runs-on: macos-15
    needs: start
    steps:
      - name: 📺 Checkout mas repo
        uses: actions/checkout@v4
        with:
          # Include all history & tags for script/version
          fetch-depth: 0
          ref: ${{env.RELEASE_TAG}}

      - name: 👢 Bootstrap
        run: |
          script/bootstrap -f

      - name: 🏗️ Build universal executable
        run: |
          script/build --universal

      - name: 📦 Package mas.pkg
        run: |
          script/package

      - name: 🚀 Upload mas.pkg
        if: ${{!env.DRY_RUN}}
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          gh release upload "${RELEASE_TAG}" .build/mas.pkg

  homebrew-tap:
    runs-on: macos-15
    needs: start
    steps:
      - name: 📺 Checkout mas repo
        uses: actions/checkout@v4
        with:
          # Include all history & tags for script/version
          fetch-depth: 0
          ref: ${{env.RELEASE_TAG}}

      - name: 🚰 Bump mas-cli/tap/mas formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: |
          brew tap mas-cli/tap
          brew bump-formula-pr \
            --tag "${RELEASE_TAG}" \
            --revision "$(git rev-list -n 1 "${RELEASE_TAG}")" \
            --no-fork \
            --no-browse \
            --online \
            --strict \
            --verbose \
            ${DRY_RUN} \
            mas-cli/tap/mas

  homebrew-core:
    # Bump homebrew-core/mas formula only if not a prerelease; all prerelease versions contain a '-'
    if: ${{!contains(env.RELEASE_TAG, '-')}}
    runs-on: macos-15
    needs: homebrew-tap
    steps:
      - name: 📺 Checkout mas repo
        uses: actions/checkout@v4
        with:
          # Include all history & tags for script/version
          fetch-depth: 0
          ref: ${{env.RELEASE_TAG}}

      - name: 🍺 Bump homebrew-core/mas formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: |
          script/brew_core_update ${DRY_RUN}
