#
# .github/workflows/release.yml
#
---
name: release
on:
  # The `push` event is used only for testing while making changes to this workflow.
  # This will be detected by the `github.event.release.name` being empty which
  # switches the logic into "dry run" mode.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]
jobs:
  release:
    runs-on: macos-14
    env:
      DRY_RUN: true
    steps:

      # Logs event details and sets `DRY_RUN` env var
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: 🔈 Log release event
        if: ${{ github.event.release.name != '' }}
        run: |
          echo "Triggered by a release publication event (wet run)"
          echo "release.name: ${{ github.event.release.name }}"
          echo "release.body: ${{ github.event.release.body }}"
          echo "DRY_RUN=false" >>$GITHUB_ENV
      - name: 🔈 Log dry run
        run: |
          echo "DRY_RUN: ${DRY_RUN}"

      - uses: actions/checkout@v4
        with:
          # A fetch-depth of 0 includes all history and tags for script/version
          fetch-depth: 0
      - name: 👢 Bootstrap
        run: script/bootstrap

      # Important to trigger a universal build first as package just works with
      # the `mas` binary in finds in the build dir.
      - name: 🏗️ Build Universal
        run: script/build --universal
      - name: 📦 macOS Package
        run: script/package
      - name: 🚀 Upload mas.pkg
        uses: actions/upload-artifact@v3
        if: ${{ env.DRY_RUN == 'false' }}
        with:
          if-no-files-found: error
          name: mas.pkg
          path: .build/mas.pkg

      - name: 🍼 Homebrew Bottles for mas tap
        run: script/bottle
      - name: 🚀 Upload Bottles
        uses: actions/upload-artifact@v3
        if: ${{ env.DRY_RUN == 'false' }}
        with:
          if-no-files-found: error
          name: homebrew-bottles
          path: |
            .build/bottles/mas-*.bottle.tar.gz

      - name: 🍺 Update Homebrew mas formula
        run: script/brew_formula_update
