#
# .github/workflows/release.yml
#
---
name: release
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/bash --noprofile --norc -eo pipefail {0}
on:
  release:
    types: [published]
env:
  DRY_RUN: ""
  GH_TOKEN: ${{github.token}}
  HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
  RELEASE_BODY: ${{github.event.release.body}}
  RELEASE_COMMITISH: ${{github.event.release.target_commitish}}
  RELEASE_NAME: ${{github.event.release.name}}
  RELEASE_TAG: ${{github.event.release.tag_name}}
jobs:
  release:
    runs-on: macos-15
    steps:
      - name: 🔈 Log real release event
        # Run only for a real release event
        if: ${{env.RELEASE_NAME}}
        run: |
          printf $'Triggered by release publication event:\nname: %s\ntag_name: %s\ntarget_commitish: %s\nbody:\n%s\n' \
            "${RELEASE_NAME}" "${RELEASE_TAG}" "${RELEASE_COMMITISH}" "${RELEASE_BODY}"

      - name: 📺 Checkout mas repo
        uses: actions/checkout@v4

      - name: 👢 Bootstrap
        run: |
          script/bootstrap -f

      - name: 🏗️ Build universal executable
        run: |
          script/build --universal

      - name: 📦 Package mas.pkg
        run: |
          script/package

      - name: 🚀 Upload mas.pkg
        if: ${{!env.DRY_RUN}}
        run: |
          gh release upload "${RELEASE_TAG}" .build/mas.pkg

      - name: 🚰 Bump mas-cli/tap/mas formula
        run: |
          brew tap mas-cli/tap
          brew bump-formula-pr \
            --tag "${RELEASE_TAG}" \
            --revision "$(git rev-parse "${RELEASE_TAG}")" \
            --no-fork \
            --no-browse \
            --online \
            --strict \
            --verbose \
            ${DRY_RUN} \
            mas-cli/tap/mas

      - name: 🍺 Bump homebrew-core/mas formula
        # Bump homebrew-core/mas formula only if not a prerelease; all prerelease versions contain a '-'
        if: ${{!contains(env.RELEASE_TAG, '-')}}
        run: |
          brew bump-formula-pr \
            --tag "${RELEASE_TAG}" \
            --revision "$(git rev-parse "${RELEASE_TAG}")" \
            --fork-org mas-cli \
            --no-browse \
            --online \
            --strict \
            --verbose \
            ${DRY_RUN} \
            mas
